### ISSUE TITLE
PhantomJS

### ISSUE THREAD

**Issue by lowski** [radar/twist#10]
It's a small suggestion rather than an issue but in my opinion it would be good to include phantomjs  as part of requirements - otherwise not all specs pass.

OS X users they need to use version from [brew](https://github.com/Homebrew/homebrew), as the one one from [brew casks](https://github.com/caskroom/homebrew-cask) won't work - `Cliver` reports it can not detect version of the binary.

**Comment by radar** [comment]
Thanks @lowski. I've updated the README.
