### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by ArmandoMendoza** [radar/twist#11]
Hi, I am reading the book "Multitenancy with Rails " which uses this app as an example. I clone the app and setup all but when run the tests, the model/chapter_spec.rb fail with this error:

> undefined method `process_markdown!' for #<Class:0x00000005e24fc8>

I searched this method in the code but i cant find it, I suppose it belong to redcarpet gem.

**Comment by radar** [comment]
Hi @ArmandoMendoza, I'm sorry for this. I had failed to push some commits to master, as well as to the markdown_book_test repo that I use for the book.

If you run these commands, you should now have green tests:

```
git pull origin master
git submodule update
bundle exec rspec spec
```

Let me know if that works for you.

**Comment by ArmandoMendoza** [comment]
Thanks @radar! Now all tests are green. By the way, the book is very good. I'm enjoying it.

**Comment by radar** [comment]
Great to hear! Thanks Armando!
