### ISSUE TITLE
errors on this pages

### ISSUE THREAD

**Issue by romenigld** [radar/twist#21]
Hello Ryan,
I was occupied doing other things these days and now I'm reading the ebook again.
I'm in the page 67.
And just for help you in the revision the error on this page presents this:
```
Failure/Error: visit links_in_email(email).first
ActionController::RoutingError:
  No route matches [GET] "/invitations/1/accept"
```

and in my terminal was complained this:
```
Failure/Error: visit accept_link

     ActionController::RoutingError:
       No route matches [GET] "/invitations/1/accept"
```

**Comment by romenigld** [comment]
A gramatic error at page 77 .
`Accounts::InvitationsControler`
needs to put Controller

**Comment by romenigld** [comment]
page 71.
the error shows different.
ebook has:
```
Failure/Error: click_button "Accept Invitation"
ActionView::Template::Error: undefined method `accepted_invitation_path' ...
```
terminal:
```
Failure/Error: <%= simple_form_for [:accepted, @invitation], as: :user do |f| %>

     ActionView::Template::Error:
       undefined method `accepted_invitation_path' ...
```

**Comment by romenigld** [comment]
page 72.
show different error. 
ebook:
```
 Failure/Error: click_button "Accept Invitation"
   NoMethodError:
     undefined method `users' for #<Account:...>

```
terminal:

```
Failure/Error: current_account.users << user

     NoMethodError:
       undefined method `users' for #<Account..>
```

**Comment by romenigld** [comment]
The another error persists when create a new model on the database. 
So on the page 73 after create the model membership and run rake db:migrate. I try to test and that error persists.
```
 rspec spec/features/accounts/accepting_invitations_spec.rb
rails aborted!
ActiveRecord::NoEnvironmentInSchemaError:

Environment data not found in the schema. To resolve this issue, run:

        bin/rails db:environment:set RAILS_ENV=test
```
So when I ran that command who was complained. Everything work's!
```
bin/rails db:environment:set RAILS_ENV=test
➜  twist git:(master) ✗ rspec spec/features/accounts/accepting_invitations_spec.rb
.

Finished in 1.54 seconds (files took 9.54 se
```

**Comment by romenigld** [comment]
page 74.
book has:
```
Failure/Error: expect(invitation.token).not_to be_blank
NoMethodError:
undefined method `token' for #<Invitation:...>
```
terminal:
```
Failure/Error: expect(invitation.token).to be_present

     NoMethodError:
       undefined method `token' for #<Invitation...>
```

**Comment by romenigld** [comment]
page 75.
Change the inheritance of the model invitation for ApplicationRecord.

app/models/invitation.rb
`class Invitation < ActiveRecord::Base`
for this:
`class Invitation < ApplicationRecord`

**Comment by romenigld** [comment]
pag 82.
ebook:
```
Failure/Error: expect(page.current_url).to eq(invitation_url)
  expected: "http://test2.example.com/invitations/<token>/accept"
       got: "http://test2.example.com/"
```

terminal:
```
 Failure/Error: expect(page.current_url).to eq(invitation_url)

       expected: "http://test2.lvh.me/invitations/<token>/accept"
            got: "http://test2.lvh.me/"
```

**Comment by romenigld** [comment]
I notice a bit modification on the page 82. On the file: `app/views/accounts/invitations/accept.html.erb` has this on the ebook:
```
<p>
You are accepting an invitation to join the <%= current_account.name %> ac\
count. </p>

```
And before was used with  `<%= @invitation.account.name %>`:
```
<p>
        You are accepting an invitation to join the <%= @invitation.account.name %> account.
    </p>
```

**Comment by radar** [comment]
Hi again :) I too have been off working on another project. 

Could you please tell me the published date listed on the 2nd page of your PDF?

**Comment by radar** [comment]
Regarding: 

```
Environment data not found in the schema. To resolve this issue, run:
```

Please make sure that you've got [this commit](https://github.com/radar/twist/commit/98174ed9a7f64918c637fdc8c530f4f372e2b444) from Twist on your own repository.

**Comment by radar** [comment]
I've just published a new edition which should fix all these issues. Thank you very much for telling me about them.

Could you please file each different one as a separate issue? This just makes it easier for me to manage when they're fixed. Thanks!

**Comment by romenigld** [comment]
the version of the date is 2016-11-24.
And yes this have in the rails_helper.rb
```
config.before(:suite) do
    DatabaseCleaner.strategy = :truncation
    DatabaseCleaner.clean_with :truncation, except: %w(ar_internal_metadata)
  end
```
And I'm sorry for put this lot of error in just one issue. I put this here because I think it was a fool errors. So when I see a more important error I put in another issue. Like the other error I post.
I download the new version and I will see these days. Thank's for reply, have a nice day!!

**Comment by radar** [comment]
Thanks :) I hope you have a good day to.
