### ISSUE TITLE
undefined local variable or method `current_account' for...

### ISSUE THREAD

**Issue by romenigld** [radar/twist#24]
Hello Ryan,
I'm reading your book again from the beginning and I'm at on the page 67 and the error was different. 
I don't know what to do for continue.
```
rspec spec/features/accounts/accepting_invitations_spec.rb                                                                           
F

Failures:

  1) Accepting invitations accepts an invitation
     Failure/Error: You have been invited to join the <%= current_account.name %> account on Twist.

     ActionView::Template::Error:
       undefined local variable or method `current_account' for #<#<Class:0x007ff321520370>:0x007ff321513f58>
       Did you mean?  current_cycle
```
I'm doing right now a commit like to "Need to fix page 67" and my GitHub is [romenigld](https://github.com/romenigld/twist)

**Comment by radar** [comment]
Hey @romenigld: do you have a repo that I can clone down to see this issue?

**Comment by romenigld** [comment]
Hello Ryan, I put there in the last line.
But take here too: https://github.com/romenigld/twist

**Comment by radar** [comment]
Thanks! This appears to be an issue in the book. That `invite.html.erb` template should use the account from the invitation object. The correct template is this:

```erb
<p>
  You have been invited to join the <%= @invitation.account.name %> account on Twist.
</p>
<p>
  <% accept_url = accept_invitation_url(
      @invitation,
      subdomain: @invitation.account.subdomain
  ) %>
  <%= link_to "Accept Invitation", accept_url %>
</p>
```

I've just released an updated edition of the book with that fix included. Thanks for letting me know about it. If there's anything else that doesn't work, please let me know about that too :)

**Comment by romenigld** [comment]
Yes, now it's going like the ebook.
And if I doesn't work I will tell you.
Thank's for reply!
